#!/usr/bin/env python
#=========================================================================
# imul-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --impl              {fl,base,alt}
#  --input dataset     {small,large,lomask,himask,lohimask,sparse}
#  --trace             Display line tracing
#  --stats             Display statistics
#  --dump-vcd          Dump VCD to imul-<impl>-<input>.vcd
#
# Author : Christopher Batten, Shunning Jiang
# Date   : February 5, 2015
#

# Hack to add project root to python path

import os
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + "pymtl.ini" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re

from random import randint, seed

seed(0xdeadbeef)

from pymtl3 import *
from pymtl3.stdlib.test_utils import config_model_with_cmdline_opts
from pymtl3.passes.backends.verilog import VerilogPlaceholderPass

from lab1_imul.IntMulFL   import IntMulFL
from lab1_imul.IntMulBase import IntMulBase
from lab1_imul.IntMulAlt  import IntMulAlt

from lab1_imul.test.IntMulFL_test import TestHarness

#-------------------------------------------------------------------------
# mk_imsg/mk_omsg
#-------------------------------------------------------------------------

# Make input message, truncate ints to ensure they fit in 32 bits.

def mk_imsg( a, b ):
  return concat( Bits32( a, trunc_int=True ), Bits32( b, trunc_int=True ) )

# Make output message, truncate ints to ensure they fit in 32 bits.

def mk_omsg( a ):
  return Bits32( a, trunc_int=True )

#----------------------------------------------------------------------
# Data Set: random small
#----------------------------------------------------------------------

random_small_msgs = []
for i in range(50):
  a = randint(0,100)
  b = randint(0,100)
  random_small_msgs.extend([ mk_imsg( a, b ), mk_omsg( a * b ) ])

small_pos_pos_msgs = [
   mk_imsg(  2,  3 ), mk_omsg(   6 ),
   mk_imsg(  4,  5 ), mk_omsg(  20 ),
   mk_imsg(  3,  4 ), mk_omsg(  12 ),
   mk_imsg( 10, 13 ), mk_omsg( 130 ),
   mk_imsg(  8,  7 ), mk_omsg(  56 ),
]

zero_one_neg_msgs = [
  mk_imsg(  0,  1 ), mk_omsg(   0 ),
  mk_imsg(  0, -1 ), mk_omsg(   0 ),
  mk_imsg(  1,  1 ), mk_omsg(   1 ),
  mk_imsg(  1, -1 ), mk_omsg(  -1 ),
  mk_imsg( -1,  1 ), mk_omsg(  -1 ),
  mk_imsg( -1,  0 ), mk_omsg(   0 ),
  mk_imsg( -1, -1 ), mk_omsg(   1 ),
  mk_imsg(  0,  0 ), mk_omsg(   0 ),
  mk_imsg(  1,  0 ), mk_omsg(   0 ),
]

small_neg_pos_msgs = [
   mk_imsg( -3,  3 ), mk_omsg(  -9 ),
   mk_imsg( -7,  9 ), mk_omsg( -63 ),
   mk_imsg( -6,  7 ), mk_omsg( -42 ),
   mk_imsg(-14,  9 ), mk_omsg(-126 ),
   mk_imsg( -6,  3 ), mk_omsg( -18 ),
]

small_pos_neg_msgs = [
   mk_imsg( 3,  -3 ), mk_omsg(  -9 ),
   mk_imsg( 9,  -7 ), mk_omsg( -63 ),
   mk_imsg( 7,  -6 ), mk_omsg( -42 ),
   mk_imsg( 9, -14 ), mk_omsg(-126 ),
   mk_imsg( 3,  -6 ), mk_omsg( -18 ),
]

small_neg_neg_msgs = [
   mk_imsg( -3,  -3 ), mk_omsg(   9 ),
   mk_imsg( -9,  -7 ), mk_omsg(  63 ),
   mk_imsg( -7,  -6 ), mk_omsg(  42 ),
   mk_imsg( -9, -14 ), mk_omsg( 126 ),
   mk_imsg( -3,  -6 ), mk_omsg(  18 ),
]

large_pos_pos_msgs = [
  mk_imsg( 1446762652,  4567432543 ), mk_omsg( 2519043556 ),
  mk_imsg( 6524278908,  2533757615 ), mk_omsg( 1462301892 ),
  mk_imsg( 5437658716,  5376427652 ), mk_omsg(  265465712 ),
  mk_imsg( 7525438628,  6524687524 ), mk_omsg( 1255213328 ),
  mk_imsg( 6536426982,  2543686865 ), mk_omsg( 2364061894 )
]

large_pos_neg_msgs = [
  mk_imsg( 1446762652,  -4567432543 ), mk_omsg(  1775923740 ),
  mk_imsg( 6524278908,  -2533757615 ), mk_omsg( -1462301892 ),
  mk_imsg( 5437658716,  -5376427652 ), mk_omsg(  -265465712 ),
  mk_imsg( 7525438628,  -6524687524 ), mk_omsg( -1255213328 ),
  mk_imsg( 6536426982,  -2543686865 ), mk_omsg(  1930905402 )
]

large_neg_pos_msgs = [
  mk_imsg( -1446762652,  4567432543 ), mk_omsg(  1775923740 ),
  mk_imsg( -6524278908,  2533757615 ), mk_omsg( -1462301892 ),
  mk_imsg( -5437658716,  5376427652 ), mk_omsg(  -265465712 ),
  mk_imsg( -7525438628,  6524687524 ), mk_omsg( -1255213328 ),
  mk_imsg( -6536426982,  2543686865 ), mk_omsg(  1930905402 )
]

large_neg_neg_msgs = [
  mk_imsg( -1446762652,  -4567432543 ), mk_omsg( -1775923740 ),
  mk_imsg( -6524278908,  -2533757615 ), mk_omsg(  1462301892 ),
  mk_imsg( -5437658716,  -5376427652 ), mk_omsg(   265465712 ),
  mk_imsg( -7525438628,  -6524687524 ), mk_omsg(  1255213328 ),
  mk_imsg( -6536426982,  -2543686865 ), mk_omsg( -1930905402 )
]

low_bit_masked_msgs = [
    mk_imsg(-2113929216, -119537664), mk_omsg(0),
    mk_imsg(-16777216, -90177536), mk_omsg(0),
    mk_imsg(-520093696, -56623104), mk_omsg(0),
    mk_imsg(-2147483648, -945815552), mk_omsg(0),
    mk_imsg(-134217728, -2147483648), mk_omsg(0),
]

middle_bit_masked_msgs = [
    mk_imsg(-2147483647, -536870907), mk_omsg(1610612741),
    mk_imsg(-67108854, -536870908), mk_omsg(2952790056),
    mk_imsg(-134217718, -2147483647), mk_omsg(4160749578),
    mk_imsg(-536870912, -536870898), mk_omsg(1073741824),
    mk_imsg(-2147483633,-1073741816), mk_omsg(1073741944),
]

sparse_number_msgs = [
    mk_imsg(-2146566143, -536608763), mk_omsg(1615462405),
    mk_imsg(-268402422, -536870908), mk_omsg(2147615784),
    mk_imsg(-1006631862, -2147479551), mk_omsg(3292832842),
    mk_imsg(-536870912, -536805362), mk_omsg(1073741824),
    mk_imsg(-2147483633, -1073741432), mk_omsg(1073747704),
]

dense_number_msgs = [
    mk_imsg(-1124074371, -273940491), mk_omsg(939271841),
    mk_imsg(-33576982, -268435468), mk_omsg(2013536520),
    mk_imsg(-67207190, -1), mk_omsg(67207190),
    mk_imsg(-335601665, -327352338), mk_omsg(462602258),
    mk_imsg(-206917473, -548038657), mk_omsg(2331948897),
]

trigger_corner_cases_msgs = [
    mk_imsg(-2146566143, -536608763), mk_omsg(1615462405),
    mk_imsg(-268402422, 536870908), mk_omsg(-2147615784),
    mk_imsg(-1006631862, -2147479551), mk_omsg(3292832842),
    mk_imsg(-536870912, -536805362), mk_omsg(1073741824),
    mk_imsg(-2147483633, 1073741432), mk_omsg(-1073747704),
]

#-------------------------------------------------------------------------
# Command line processing
#-------------------------------------------------------------------------

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",    action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl", default="fl",
    choices=["fl","base","alt"] )

  p.add_argument( "--input", default="small",
    choices=["small", "small_pos_pos_msgs", "zero_one_neg_msgs", "small_neg_pos_msgs",
    "small_pos_neg_msgs", "small_neg_neg_msgs", "large_pos_pos_msgs", "large_pos_neg_msgs",
    "large_neg_pos_msgs", "large_neg_neg_msgs", "low_bit_masked_msgs", "middle_bit_masked_msgs",
    "sparse_number_msgs", "dense_number_msgs", "trigger_corner_cases_msgs"] )

  p.add_argument( "--trace",     action="store_true" )
  p.add_argument( "--stats",     action="store_true" )
  p.add_argument( "--translate", action="store_true" )
  p.add_argument( "--dump-vcd",  action="store_true" )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#-------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------

def main():
  opts = parse_cmdline()

  # Create the input pattern

  inputs  = None

  # ''' LAB TASK '''''''''''''''''''''''''''''''''''''''''''''''''''''''''
  # Use additional if statements to set the inputs appropriately based on
  # the --input command line option.
  # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

  if opts.input == "small":
    inputs = random_small_msgs

  if opts.input == "small_pos_pos_msgs":
    inputs = small_pos_pos_msgs

  if opts.input == "zero_one_neg_msgs":
    inputs = zero_one_neg_msgs

  if opts.input == "small_neg_pos_msgs":
    inputs = small_neg_pos_msgs

  if opts.input == "small_pos_neg_msgs":
    inputs = small_pos_neg_msgs

  if opts.input == "small_neg_neg_msgs":
    inputs = small_neg_neg_msgs

  if opts.input == "large_pos_pos_msgs":
    inputs = large_pos_pos_msgs

  if opts.input == "large_pos_neg_msgs":
    inputs = large_pos_neg_msgs

  if opts.input == "large_neg_pos_msgs":
    inputs = large_neg_pos_msgs

  if opts.input == "large_neg_neg_msgs":
    inputs = large_neg_neg_msgs

  if opts.input == "low_bit_masked_msgs":
    inputs = low_bit_masked_msgs

  if opts.input == "middle_bit_masked_msgs":
    inputs = middle_bit_masked_msgs

  if opts.input == "sparse_number_msgs":
    inputs = sparse_number_msgs

  if opts.input == "dense_number_msgs":
    inputs = dense_number_msgs

  if opts.input == "trigger_corner_cases_msgs":
    inputs = trigger_corner_cases_msgs


  ninputs = len(inputs[::2])

  # Determine which model to use in the simulator

  model_impl_dict = {
    "fl"  : IntMulFL,
    "base": IntMulBase,
    "alt" : IntMulAlt,
  }

  # Check if translation is valid

  if opts.translate and not opts.impl.startswith("rtl"):
    print("\n ERROR: --translate only works with RTL models \n")
    exit(1)

  # Create test harness (we can reuse the harness from unit testing)

  th = TestHarness( model_impl_dict[ opts.impl ]() )

  th.set_param( "top.src.construct",  msgs=inputs[::2]  )
  th.set_param( "top.sink.construct", msgs=inputs[1::2] )

  # Create VCD filename

  unique_name = f"imul-{opts.impl}-{opts.input}"

  cmdline_opts = {
    'dump_vcd': f"{unique_name}" if opts.dump_vcd else '',
    'test_verilog': 'zeros' if opts.translate else '',
  }

  # Configure the test harness component

  config_model_with_cmdline_opts( th, cmdline_opts, duts=['imul'] )

  # Apply necessary passes

  th.apply( DefaultPassGroup( linetrace=opts.trace ) )

  # Reset test harness

  th.sim_reset()

  # Run simulation

  while not th.done():
    th.sim_tick()

  # Extra ticks to make VCD easier to read

  th.sim_tick()
  th.sim_tick()
  th.sim_tick()

  # Display statistics

  if opts.stats:
    print( f"num_cycles         = {th.sim_cycle_count()}" )
    print( f"num_cycles_per_mul = {th.sim_cycle_count()/(1.0*ninputs):1.2f}" )

main()

